using NUnit.Framework;

namespace AccountManagement.UI.QueryModels.Updaters.Tests.AccountQueryModelTests
{
    public class AfterUserChangesAccountPassword_Generators : AfterUserChangesAccountPassword
    {
        [SetUp]
        public void RewireForGenerators()
        {
            QueryModelTestWiringHelper.ReplaceDocumentDbQuerymodelsReaderWithAutoGeneratedQueryModelsReader(Container);
        }
    }
}