# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Composable Toolkit
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A .Net toolkit making CQRS, Event Sourcing, Event Driven Architecture, VEST testing and DDD
  simpler and more productive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://composabletk.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mlidbom
livereload: true

# Build settings
stylesdir: vendor-css
markdown: kramdown
#destination: ../../docs
keep_files: [apidocs]

exclude:
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _site
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - stylesdir=vendor-css
    - imagesdir=images
    - imagesoutdir=images
    - source-highlighter=pygments
    - icons=font
