source 'https://rubygems.org'

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'jekyll', '~> 3.3.1'
gem 'rake-jekyll', '~> 1.1.0'
gem 'pygments.rb'

group :jekyll_plugins do
  gem 'jekyll-asciidoc'
     gem 'jekyll-livereload'
end
