= Composable Toolkit

== Vest testing framework

== Event store
* Full VEST Testing Support
* Comprehensive refactoring support keeps your code base clean and flexible.
* No pollution of public interfaces with event applier methods.
* Easily build complex aggregates by nesting components and entity collection to arbitrary depths.
* Reduce the number of event appliers by an order of magnitude through semantic event routing.
* Generate query models from the event stream with excellent performance. Minimize downtime and development friction by minimizing the number of persisted Query Models.


=== Refactoring support
Maintain flexibility and a clean code base with comprehensive refactoring support.

==== Newtonsoft.JSON supported refactorings
* Take effect immediately without any need to wait for batches.
* Completely encapsulated. Clients of the event store see only refactored events and aggregates.
* Some possible refactorings
** Rename properties and fields.
** Add properties including calculating values for historical events that originally did not have the new property.

====  Event Stream migrations
* Take effect immediately without any need to wait for batches.
* Completely encapsulated. Clients of the event store see only refactored streams and aggregates.
* Supported Refactorings
** Rename event
** Replace legacy event with new event(s).
** Insert new event(s) before or after existing event.
* Persist migrations to storage
** On-line persisting of in-memory migrations.
** Remove legacy events, handlers, and persisted migrations from your codebase.
** Complete history including refactorings is retained in storage.
** Comprehensively test the refactorings in-memory before choosing to persist them.






== Semantic Event Routing
* Declarative programming model.
* Powerful tool for designing and reasoning about a domain.
* Decouple Listeners from publishers
* Reduce number of event appliers (Usually by an order of magnitude or more)
* Reduce the number of required event handlers.
* Eliminate the need for new event appliers to handle new variations on existing events.
* Reduce the need for new event handlers for new variations on existing events.