== Core beliefs

We believe that if you are considering using our tools you really should read all of this page to determine if it is likely to be a good fit for you and your organization. You may have trouble seeing the relevance at first, but it should all fit together as a whole in the end.

We believe that people should always be a vital consideration::

We believe that our level of success of failure in collaborative endeavors hinges more on the humans, relationships and cultures involved than on any other factor. On how well we collaborate, communicate, motivate etc. We believe that this in turn hinges on our understanding of ourselves, on our understanding of human nature, on our understanding of the human mind and its properties, strengths and weaknesses. We believe that this understanding must include our drives, instincts, emotions and feelings. We believe that whenever we lose sight of this as a vital consideration when making choices we are likely to make choices with poor outcomes. This includes software design choices.

We believe in the necessity of accepting complexity and letting go of certainty::

We believe we all instinctively prefer simplicity, certainty and absolutes. That this is a trait that was likely adaptive when we lived as hunter gatherers. We believe that this is no longer a primarily adaptive trait. We believe that succumbing to this trait cripples our ability to see the true complexity of the reality we have before us. Rather than clear cut wrong and right ways to do things we believe that we face great complexity and a great amount of possible choices in every situation. We believe that we must accept the weight of the uncertainty of this reality in order to make good choices.

We believe in the superiority of motivated belief over dichotomies and absolutes::

We believe that succumbing to the desire to think and debate in terms of simple good versus bad dichotomies or absolutes such as "best way" is crippling. That it cripples not only our own understanding, but even more so our ability to collaborate in teams and larger communities. We believe that it is far better to say: "We believe" and then motivate that belief, than to state something as a fact without motivation. We believe that we must resist the temptation to talk about good versus bad and wrong versus right. We believe that there is no such thing as a "best" way to do anything, rather every option has a complex set of consequences in any specific set of circumstances which we never fully understand. We believe that we should abandon the false simplicity of right versus wrong dichotomies and absolutes such as "best".

We believe that development should focus on shared mental models designed for humans::

We believe that developing software is first and foremost a process of collaboratively designing and communicating shared mental models.  We believe that our focus must be on the quality and clarity of our mental models and the clarity and expressiveness of the code that we use to communicate these mental models to each other and our future selves. That the quality of a design is determined by how easily the totality of the mental models that it contains can be learned, communicated, and modified by human beings.

We believe that the primary limiting factor is the mental burden imposed by the totality of our shared mental models::

We believe that in the majority of software development situations a lack of focus on the quality of the mental models is ultimately the primary factor limiting progress. That progress slows and ultimately stalls when the totality of our mental models fall into a state where the humans developing them can no longer effectively learn, understand, modify and communicate them. We believe that if we continually refactor our mental models to fit the human mind it is possible to maintain progress indefinitely without stalling and with limited slowdown even when facing immensely complicated software. We believe that this is the implicit principle underpinning approaches such as Domain Driven Design and principles such as SOLID.