= FAQ

What if we need extreme querying scalability?::
Given this requirement we assume that you are willing to sacrifice some level of consistency in query results. Given that these are possible options:
* Maintain query models in any storage with sufficient scalablility.
* Add a layer on top of your querying API that makes use of a distributed cache.

What if we need extreme write side scalability?::
If only a small subset of your data requires this level of write scalability, consider implementing only that part using other tools. If most of your data requires that level of scalability we would not recommend using our tools.

Why do you enforce transactions for all update?::
Because it is our opinion that without transactions you have to sacrifice either reliability or simplicity/maintainability and we prioritize those over scalability and performance.

Why do you enforce exacly once delivery for domain events?::
Because it is our opinion that without exactly once delivery you have to sacrifice either reliability or simplicity/maintainability and we prioritize those over scalability and performance.

Isn't exactly once delivery impossible?::
No. All arguments to that effect that we have encountered reason by disallowing transactions and/or message deduplication. Only through imposing this artificial constraint does exactly once delivery become "impossible". Exactly once  == at least once + deduplication + transactions.

