namespace Composable.KeyValueStorage.AutoGenerated
{
    public interface IDocumentGenerator { }


    public interface IDocumentGenerator<out TDocument> : IDocumentGenerator
    {
        TDocument TryGenerate(object id);
    }    
}