using AccountManagement.UI.QueryModels.DocumentDB.Updaters.ContainerInstallers;
using AccountManagement.UI.QueryModels.EventStore.Generators.ContainerInstallers;
using AccountManagement.UI.QueryModels.Services;
using Castle.Windsor;
using Castle.Windsor.Installer;
using Composable.CQRS.Windsor;

namespace AccountManagement.UI.QueryModels.EventStore.Generators.Tests
{
    public static class QueryModelTestWiringHelper
    {
        public static void ReplaceDocumentDbQuerymodelsReaderWithAutoGeneratedQueryModelsReader(IWindsorContainer container)
        {
            container.Install(
                FromAssembly.Containing<AccountManagementQueryModelGeneratingQueryModelSessionInstaller>()
                );

                container.Kernel.AddHandlerSelector(
                    new KeyReplacementHandlerSelector(
                        typeof(IAccountManagementQueryModelsReader),
                            AccountManagementQuerymodelsSessionInstaller.ComponentKeys.KeyForSession,
                            AccountManagementQueryModelGeneratingQueryModelSessionInstaller.ComponentKeys.Session));
        } 
    }
}