=== Domain Driven Design with Semantic Events
I we know that A has happened, does that mean that B,C or D have also happened?
Modelling by declaring such relationships of meaning between events can enable us to construct rich views of domains.
A view that is a great complement to the classical views of data and functions.
In essense you create a forest of meaning that includes everything that can happen in the domain as well as how these events relate to each other and to the abstractions in the domain. 
Your aggregates correlete to the trees, their nested entities and components to the branches, and the concrete events raised are the leaves.

.Introduction: A birds eye view of a recruitment domain
[source]
----
include::semantic-events.cs[tag=recruitment-birds-eye-view]
----
Once  we become accustomed to reading this view of a domain it turns out to be quite rich and concise. In this short sample we can see that:

<1> We have two types of users that perform actions in the system. Job seekers and Recruiters.
<2> There is an aggregate in our domain called Recruitment
<3> A recruitment can be registered which 
<4> -- is performed by a recruiter
<5> -- creates the recruitment
<6> A Recruitment contains entities called Applications
<7> A Job Seeker can be applied for the position a recruitment manages which
<8> -- creates an Application
<9> -- is done by the Job Seekers themselves

