using AccountManagement.UI.QueryModels.Generators.ContainerInstallers;
using AccountManagement.UI.QueryModels.Services;
using Castle.Windsor;
using Castle.Windsor.Installer;
using Composable.CQRS.Windsor;

namespace AccountManagement.UI.QueryModels.Updaters.Tests
{
    public static class QueryModelTestWiringHelper
    {
        public static void ReplaceDocumentDbQuerymodelsReaderWithAutoGeneratedQueryModelsReader(IWindsorContainer container)
        {
            container.Install(
                FromAssembly.Containing<AccountManagementQueryModelGeneratingQueryModelSessionInstaller>()
                );

                container.Kernel.AddHandlerSelector(
                    new KeyReplacementHandlerSelector(
                        typeof(IAccountManagementQueryModelsReader),
                            QueryModels.Updaters.ContainerInstallers.AccountManagementQuerymodelsSessionInstaller.ComponentKeys.KeyForSession,
                            QueryModels.Generators.ContainerInstallers.AccountManagementQueryModelGeneratingQueryModelSessionInstaller.ComponentKeys.Session));
        } 
    }
}